In [11]:
import tensorflow as tf
import numpy as np


In [12]:
x = tf.constant([1., 2., 3.])
y = tf.constant([3., 2., 1.])

Use tf.add to add two numbers

In [13]:
sum=tf.add(x,y)
print(sum)

tf.Tensor([4. 4. 4.], shape=(3,), dtype=float32)


Use tf.subtract to sub two numbers

In [14]:
sub=tf.subtract(x,y)
print(sub)

tf.Tensor([-2.  0.  2.], shape=(3,), dtype=float32)


Multiply use tf.multiply

In [15]:
mul=tf.multiply(x,y)
print(mul)

tf.Tensor([3. 4. 3.], shape=(3,), dtype=float32)


Divide two numbers using tf.divide

In [16]:
div=tf.divide(x,y)
print(div)

tf.Tensor([0.33333334 1.         3.        ], shape=(3,), dtype=float32)


The dot product can be computed as follows:

In [17]:
dot_product = tf.reduce_sum(tf.multiply(x, y))
dot_product.numpy()

np.float32(10.0)

Next, let's find the index of the minimum and maximum elements:

In [28]:
x = tf.constant([10, 11, 3, 9])
tf.argmin(x).numpy()

np.int64(2)

the index of the maximum value is computed using tf.argmax()

In [30]:
tf.argmax(x).numpy()

np.int64(0)

Concatenate the two matrices:

In [37]:
x = [[3,6,9], [7,7,7]]
y = [[4,5,6], [5,5,5]]

In [38]:
tf.concat([x, y], 0).numpy()

array([[3, 6, 9],
       [7, 7, 7],
       [4, 5, 6],
       [5, 5, 5]], dtype=int32)

Use the following code to concatenate the matrices column-wise:


In [39]:
tf.concat([x, y], 1).numpy()

array([[3, 6, 9, 4, 5, 6],
       [7, 7, 7, 5, 5, 5]], dtype=int32)

Stack the x matrix using the stack function:

In [40]:
tf.stack(x, axis=1).numpy()

array([[3, 7],
       [6, 7],
       [9, 7]], dtype=int32)

Now, let' see how to perform the reduce_mean operation:

In [42]:
x = tf.Variable([[1.0, 5.0], [2.0, 3.0]])
x.numpy()

array([[1., 5.],
       [2., 3.]], dtype=float32)

Compute the mean value of x

In [43]:
tf.reduce_mean(input_tensor=x).numpy()

np.float32(2.75)

Compute the mean across the column; that is,

In [44]:
tf.reduce_mean(input_tensor=x, axis=1, keepdims=True).numpy()

array([[3. ],
       [2.5]], dtype=float32)

Compute the mean across the row; that is,

In [46]:
tf.reduce_mean(input_tensor=x, axis=0).numpy()

array([1.5, 4. ], dtype=float32)

Compute the softmax probabilities:

In [47]:
x = tf.constant([7., 2., 5.])
tf.nn.softmax(x).numpy()

array([0.8756006 , 0.00589975, 0.11849965], dtype=float32)

Now, we'll look at how to compute the gradients.

In [49]:
def square(x):
  return tf.multiply(x, x)

The gradients can be computed for the preceding square function using
tf.GradientTape, as follows

In [52]:
with tf.GradientTape(persistent=True) as tape:
  print(square(6.).numpy())

36.0
